### ISSUE TITLE
"Index out of bounds" for incomplete regex terminal

### ISSUE THREAD

**Issue by aengelberg** [mhuebert/instaparse-live#1]
Given this specific grammar:

```

a = #'
```

(the newline at the beginning is important)

The output shows `Error: index out of bounds` instead of an average "grammar not parsed properly" error. I'm not sure whether this is a bug in instaparse-live or instaparse-cljs, I will be able to look into this more later.

Thank you for making this awesome project!
--Alex

**Comment by aengelberg** [comment]
Update: The bug seems to occur with ANY parse failure if the grammar begins with a newline.

It appears to be a bug with instaparse-cljs; I'll post an issue on there as well.

**Comment by mhuebert** [comment]
Good catch. I saw that error often while working locally.

Incidentally, I realized today that I don't really understand how to effectively debug issues like this. Is there a straightforward way to edit the code of a dependency like instaparse-cljs (say, to insert print statements) while running this project using lein-figwheel, and have those updates trigger a reload? In javascript/NPM-land, it's possible to go into the node_modules folder and make little edits for things like this. 

(I learned today that I could fetch instaparse-cljs locally and then run lein pom / jar / install in order to use the local copy as a dependency, but that doesn't seem optimal.)

**Comment by aengelberg** [comment]
Last night I was playing with instaparse-live and found some issues with instaparse-cljs, so to make some quick fixes (and submit a PR) I ended up in a similar workflow; I would make changes to instaparse-cljs, run `lein install` (I think the pom / jar tasks happen automatically), then switch over to instaparse-live and run `lein figwheel`, really so I can get a ClojureScript REPL, or play with the live parsing to verify the behavior of instaparse-cljs. I'm similarly curious whether there is a better way. I also ran into problems where I seemed to be running old instaparse-cljs code even after `lein install`; after a half hour of frustration I realized I had to `lein clean` so figwheel wasn't using the old subproject code.

In JVM Clojure land, you can use the [checkouts](https://github.com/technomancy/leiningen/blob/master/doc/TUTORIAL.md#checkout-dependencies) directory and create symlinks to other projects. This slightly improves the "lein install" workflow, as you can reload code from the subprojects in your REPL. I have yet to research how this translates to cljs; I'm doubtful that figwheel would be smart about reloading code from subprojects.

**Comment by aengelberg** [comment]
This is resolved in instaparse-cljs `1.3.5.1-SNAPSHOT`
